- name: Local Provisioning
  hosts: localhost
  connection: local

  # Variables
  vars:
    src_dir: /usr/local/
    go_version: go1.10.linux-amd64

  tasks:
    - name: install packages
      yum: name={{ item }} state=installed
      with_items:
        - git
        - gcc

    # Download Golang
    - name: Download Golang to /usr/local
      get_url: url="https://storage.googleapis.com/golang/{{go_version}}.tar.gz" dest=/usr/local

    - unarchive:
        src=/usr/local/{{go_version}}.tar.gz
        dest=/usr/local/

    - file: path=/usr/local/{{go_version}}.tar.gz
        state=absent

    # Install mattes/migrate (Database migrations. CLI and Golang library.)
    - name: Install mattes/migrate (Database migrations. CLI and Golang library.)
      get_url: url="https://github.com/mattes/migrate/releases/download/v3.0.1/migrate.linux-amd64.tar.gz" dest=/usr/local/bin

    - unarchive:
        src=/usr/local/bin/migrate.linux-amd64.tar.gz
        dest=/usr/local/bin

    - file: path=/usr/local/bin/migrate.linux-amd64.tar.gz
        state=absent

    - name: Rename "migrate.linux-amd64" to "migrate"
      command: mv /usr/local/bin/migrate.linux-amd64 /usr/local/bin/migrate

    # Install godo (golang build tool in the spirt of rake, gulp)
    - name: Install godo (golang build tool in the spirt of rake, gulp)
      command: go get -u gopkg.in/godo.v2/cmd/godo
