version: '3'
services:

  # Application Server Container
  web:
    # build Dockerfile
    build: ./web
    ports:
    - "1323:1323"
    # mount host directory HostPath:ContainerPath
    volumes:
      - ${GOPATH}/src/github.com/wmetaw/go-ddd-on-echo:/go/src/github.com/wmetaw/go-ddd-on-echo
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mysql-server
    links:
      - mysql-server
    command: go run /go/src/github.com/wmetaw/go-ddd-on-echo/main.go

  # Mysql Server Container
  mysql-server:
    image: mysql:5.7.21
    expose:
      - 3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_HOST: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
